# Generated by Django 5.1.5 on 2025-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
    ]
