# Generated by Django 5.1.5 on 2025-02-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role_app', '0002_remove_rolepermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
            preserve_default=False,
        ),
    ]
