# Generated by Django 5.1.5 on 2025-02-04 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role_app', '0003_rolepermission_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='granted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('user', 'role', 'permission')},
        ),
    ]
