# Generated by Django 5.1.5 on 2025-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0004_alter_rolepermission_granted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
